# 
# Build & push azure container app
#

name: __Build & Publish & Push Container App

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
    secrets:
      container_registry:
        required: true
      container_registry_id:
        required: true
      container_registry_pw:
        required: true
      azure_credentials:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.container_registry }}
      CONTAINER_REGISTRY_ID: ${{ secrets.container_registry_id }}
      CONTAINER_REGISTRY_PW: ${{ secrets.container_registry_pw }}
    
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      #
      # Builds the Docker image.
      #
      - name: Build image
        run:  | 
          ./scripts/build_image.sh ${{ inputs.app-name }}

      #
      # Publishes the Docker image to the container registry.
      #
      - name: Publish image to container registry
        run:  |
          ./scripts/push_image.sh ${{ inputs.app-name }}

      - name: 'Az CLI login'
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: 'Push image to container app environment'
        uses: Azure/cli@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az extension add -n containerapp
            echo "Starting Deployment"
            az containerapp update -n ${{ inputs.app-name}} -g ltl-aca-rg -i ${{ secrets.container_registry }}/${{ inputs.app-name }}:${{ github.sha }} --debug 
